User.create(name: "Shane Williams", email: "shanewilliams@gmail.com", password: "password", phone_number: "6145554444", image_url: "")
User.create(name: "Nuke DaFarta", email: "nuke@gmail.com", password: "password", phone_number: "6146664444", image_url: "")
User.create(name: "Eva DaGoon", email: "eva@gmail.com", password: "password", phone_number: "6145553333", image_url: "")

Patient.create(name: "Johnny", user_id: 1, notes: "Take meds with orange juice", image_url: "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/11/931/524/AP20307373014376.jpg?ve=1&tl=1")
Patient.create(name: "Chrissy", user_id: 2, notes: "Take meds with grape juice", image_url: "https://akns-images.eonline.com/eol_images/Entire_Site/2021425/rs_1200x1200-210525134631-1200x1200.this-is-us-chrissy-metz-lp.52521.jpg?fit=around%7C1200:1200&output-quality=90&crop=1200:1200;center,top")
Patient.create(name: "Melanie", user_id: 2, notes: "Dont speak too loudly", image_url: "https://static.abcotvs.com/kgo/images/cms/111419-kgo-ap-melanie-martinez-img.jpg")
Patient.create(name: "Barb", user_id: 3, notes: "Administer meds with FOOD", image_url: "https://www.nme.com/wp-content/uploads/2016/11/2016_StrangerThings_1_Barb_Netflix_090816-1.jpg")
Patient.create(name: "Dani", user_id: 1, notes: "Dislikes orange juice. ", image_url: "https://avatars.githubusercontent.com/u/13294925?v=4")
Patient.create(name: "Rob", user_id: 3, notes: "Take meds with orange juice", image_url: "https://cdn.cnn.com/cnnnext/dam/assets/200408115224-rob-lowe-joe-exotic-instagram-super-tease.jpg")

Drug.create(name: "Advil", description: "Pain reliever", image_url: "https://img.medscapestatic.com/pi/features/drugdirectory/octupdate/WRH01500.jpg", frequency: "As Needed", notes: "Dont mix with Haldol", patient_id: 1)
Drug.create(name: "Haldol", description: "Agitation", image_url: "https://www.buy-pharma.md/img/uploads/23623-Haldol-Haloperidol-Oral-Solution.jpg", frequency: "As Needed", notes: "", patient_id: 2)
Drug.create(name: "Tylenol", description: "Pain reliever", image_url: "https://www.drugs.com/images/pills/fio/MCC04492.JPG", frequency: "As Needed", notes: "", patient_id: 2)
Drug.create(name: "Morphine", description: "Pain reliever", image_url: "https://www.banyantreatmentcenter.com/wp-content/uploads/2021/07/effects-of-morphine-on-the-body.gif", frequency: "As Needed", notes: "", patient_id: 1)
Drug.create(name: "Seroquel", description: "Anxiety", image_url: "https://media.npr.org/assets/img/2018/08/06/gettyimages-94865845seroquel_vert-e7afbea83d45857973cab3f35744c47419891827.jpg", frequency: "As Needed", notes: "", patient_id: 3)
Drug.create(name: "Pepto", description: "Pink in color.Acid Reducer, helps with the runs", image_url: "https://storage.googleapis.com/images-sof-prd-9fa6b8b.sof.prd.v8.commerce.mi9cloud.com/product-images/detail/00056100008729.jpg", frequency: "As Needed", notes: "", patient_id: 4)
